CREATE TABLE Client (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(200) CHECK (LENGTH(name) BETWEEN 3 AND 200) NOT NULL
);

CREATE TABLE Planet (
    id VARCHAR(100) PRIMARY KEY CHECK (id ~ '^[A-Z0-9]+$'),
    name VARCHAR(500) CHECK (LENGTH(name) BETWEEN 1 AND 500) NOT NULL
);

CREATE TABLE Ticket (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC') NOT NULL,
    client_id BIGINT REFERENCES Client(id) NOT NULL,
    from_planet_id VARCHAR(100) REFERENCES Planet(id) NOT NULL,
    to_planet_id VARCHAR(100) REFERENCES Planet(id) NOT NULL
);